/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leotify;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nadina Mazzoni
 */
public class Leotify extends javax.swing.JFrame {

    /**
     * Creates new form Leotify
     */
    public Leotify() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        AdminUsuario a_u;
        AdminArtista a_a;
        crear_album_bt.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro_usuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre_nuevo_usuario = new javax.swing.JTextField();
        apellido_nuevo_usuario = new javax.swing.JTextField();
        usuario_nuevo_usuario = new javax.swing.JTextField();
        fecha_nuevo_usuario = new datechooser.beans.DateChooserCombo();
        contrasena_nuevo_usuario = new javax.swing.JPasswordField();
        crear_usuario = new javax.swing.JButton();
        Registro_artista = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombre_nuevo_artista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        apellido_nuevo_artista = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        usuario_nuevo_artista = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fecha_nuevo_artista = new datechooser.beans.DateChooserCombo();
        jLabel12 = new javax.swing.JLabel();
        contrasena_nuevo_artista = new javax.swing.JPasswordField();
        crear_usuario1 = new javax.swing.JButton();
        Log_in_usuario = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        usuario_login_usuario = new javax.swing.JTextField();
        contrasena_login_usuario = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        Log_in_artista = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        usuario_login_artista = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        contrasena_login_artista = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        Artista = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        label_atista = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_seguidores = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_albumes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_sencillos = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        Agregar_sencillo = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nombre_agregar_sencillo = new javax.swing.JTextField();
        ano_agregar_sencillo = new javax.swing.JTextField();
        duracion_agregar_sencillo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Agregar_album = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nombre_crear_album = new javax.swing.JTextField();
        ano_crear_album = new javax.swing.JTextField();
        crear_album_bt = new javax.swing.JButton();
        Agregar_cancion = new javax.swing.JDialog();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        nombre_agregar_cancion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        ano_agregar_cancion = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        duracion_agregar_cancion = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        Usuario = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        label_usuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_rep_playlist = new javax.swing.JList<>();
        reproducir_playlist = new javax.swing.JButton();
        b_historial = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_artistas_a_seguir = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        barra_reproduccion = new javax.swing.JProgressBar();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        Crear_playlist = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        nombre_crear_playlist = new javax.swing.JTextField();
        genero_crear_playlist = new javax.swing.JTextField();
        fecha_crear_playlist = new datechooser.beans.DateChooserCombo();
        jButton12 = new javax.swing.JButton();
        Agregar_canciones_al_playlist = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        lista_todas_las_canciones = new javax.swing.JList<>();
        jButton14 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        log_in_usuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        log_in_artista = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        Registro_usuario.setTitle("Registro usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registro Usuario");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Fecha de nacimiento:");

        jLabel6.setText("Contraseña:");

        crear_usuario.setText("Crear");
        crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Registro_usuarioLayout = new javax.swing.GroupLayout(Registro_usuario.getContentPane());
        Registro_usuario.getContentPane().setLayout(Registro_usuarioLayout);
        Registro_usuarioLayout.setHorizontalGroup(
            Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Registro_usuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(apellido_nuevo_usuario))
                            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(usuario_nuevo_usuario))
                            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_nuevo_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contrasena_nuevo_usuario))))
                    .addGroup(Registro_usuarioLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(Registro_usuarioLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(crear_usuario)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Registro_usuarioLayout.setVerticalGroup(
            Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registro_usuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellido_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usuario_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fecha_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contrasena_nuevo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(crear_usuario)
                .addGap(32, 32, 32))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Registro Artista");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido:");

        jLabel10.setText("Usuario:");

        jLabel11.setText("Fecha de nacimiento:");

        jLabel12.setText("Contraseña:");

        crear_usuario1.setText("Crear");
        crear_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Registro_artistaLayout = new javax.swing.GroupLayout(Registro_artista.getContentPane());
        Registro_artista.getContentPane().setLayout(Registro_artistaLayout);
        Registro_artistaLayout.setHorizontalGroup(
            Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registro_artistaLayout.createSequentialGroup()
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Registro_artistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Registro_artistaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Registro_artistaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(apellido_nuevo_artista))
                            .addGroup(Registro_artistaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(usuario_nuevo_artista))
                            .addGroup(Registro_artistaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_nuevo_artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Registro_artistaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contrasena_nuevo_artista))))
                    .addGroup(Registro_artistaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(crear_usuario1))
                    .addGroup(Registro_artistaLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel7)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        Registro_artistaLayout.setVerticalGroup(
            Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registro_artistaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombre_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(apellido_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(usuario_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(fecha_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Registro_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(contrasena_nuevo_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(crear_usuario1)
                .addGap(32, 32, 32))
        );

        Log_in_usuario.setTitle("Log in Usuario");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Log In Usuario");

        jLabel14.setText("Usuario:");

        jLabel15.setText("Contraseña:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Log_in_usuarioLayout = new javax.swing.GroupLayout(Log_in_usuario.getContentPane());
        Log_in_usuario.getContentPane().setLayout(Log_in_usuarioLayout);
        Log_in_usuarioLayout.setHorizontalGroup(
            Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_in_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Log_in_usuarioLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(usuario_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Log_in_usuarioLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasena_login_usuario)
                            .addGroup(Log_in_usuarioLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Log_in_usuarioLayout.setVerticalGroup(
            Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_in_usuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addGroup(Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(usuario_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Log_in_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(contrasena_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Log In Artista");

        jLabel17.setText("Usuario:");

        jLabel18.setText("Contraseña:");

        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Log_in_artistaLayout = new javax.swing.GroupLayout(Log_in_artista.getContentPane());
        Log_in_artista.getContentPane().setLayout(Log_in_artistaLayout);
        Log_in_artistaLayout.setHorizontalGroup(
            Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_in_artistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Log_in_artistaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(usuario_login_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Log_in_artistaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasena_login_artista)
                            .addGroup(Log_in_artistaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Log_in_artistaLayout.setVerticalGroup(
            Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_in_artistaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(usuario_login_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Log_in_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(contrasena_login_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Bienvenido");

        label_atista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel20.setText("Seguidores");

        jLabel21.setText("Albumes");

        jLabel22.setText("Sencillos");

        jButton3.setText("Agregar sencillo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar album");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lista_seguidores.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(lista_seguidores);

        lista_albumes.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(lista_albumes);

        lista_sencillos.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(lista_sencillos);

        jButton6.setText("Agregar canciones al album");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ArtistaLayout = new javax.swing.GroupLayout(Artista.getContentPane());
        Artista.getContentPane().setLayout(ArtistaLayout);
        ArtistaLayout.setHorizontalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistaLayout.createSequentialGroup()
                        .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_atista, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))
                    .addGroup(ArtistaLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addContainerGap())))
        );
        ArtistaLayout.setVerticalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_atista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArtistaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))))
                .addGap(18, 18, 18)
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Agregar sencillo");

        jLabel24.setText("Nombre:");

        jLabel25.setText("Año:");

        jLabel26.setText("Duracion (en segundos) :");

        jButton5.setText("Crear sencillo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Agregar_sencilloLayout = new javax.swing.GroupLayout(Agregar_sencillo.getContentPane());
        Agregar_sencillo.getContentPane().setLayout(Agregar_sencilloLayout);
        Agregar_sencilloLayout.setHorizontalGroup(
            Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_sencilloLayout.createSequentialGroup()
                .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar_sencilloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_agregar_sencillo)
                            .addComponent(ano_agregar_sencillo)))
                    .addGroup(Agregar_sencilloLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton5))
                    .addGroup(Agregar_sencilloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addGap(10, 10, 10)
                        .addComponent(duracion_agregar_sencillo)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_sencilloLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(49, 49, 49))
        );
        Agregar_sencilloLayout.setVerticalGroup(
            Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_sencilloLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel23)
                .addGap(36, 36, 36)
                .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nombre_agregar_sencillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ano_agregar_sencillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Agregar_sencilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(duracion_agregar_sencillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(25, 25, 25))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("Agregar Album");

        jLabel28.setText("Nombre:");

        jLabel29.setText("Año:");

        crear_album_bt.setText("Crear album");
        crear_album_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_album_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Agregar_albumLayout = new javax.swing.GroupLayout(Agregar_album.getContentPane());
        Agregar_album.getContentPane().setLayout(Agregar_albumLayout);
        Agregar_albumLayout.setHorizontalGroup(
            Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_albumLayout.createSequentialGroup()
                .addGroup(Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar_albumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_crear_album)
                            .addComponent(ano_crear_album, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(Agregar_albumLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(crear_album_bt))
                    .addGroup(Agregar_albumLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel27)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        Agregar_albumLayout.setVerticalGroup(
            Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_albumLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel27)
                .addGap(26, 26, 26)
                .addGroup(Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(nombre_crear_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(Agregar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(ano_crear_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(crear_album_bt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Agregar canción");

        jLabel31.setText("Nombre:");

        jLabel32.setText("Año:");

        jLabel33.setText("Duracion (en segundos) :");

        jButton9.setText("Añadir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Agregar_cancionLayout = new javax.swing.GroupLayout(Agregar_cancion.getContentPane());
        Agregar_cancion.getContentPane().setLayout(Agregar_cancionLayout);
        Agregar_cancionLayout.setHorizontalGroup(
            Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_cancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar_cancionLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(10, 10, 10)
                        .addComponent(duracion_agregar_cancion, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(Agregar_cancionLayout.createSequentialGroup()
                        .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Agregar_cancionLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nombre_agregar_cancion)
                            .addComponent(ano_agregar_cancion))))
                .addContainerGap())
            .addGroup(Agregar_cancionLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Agregar_cancionLayout.setVerticalGroup(
            Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_cancionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel30)
                .addGap(34, 34, 34)
                .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(nombre_agregar_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(ano_agregar_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Agregar_cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(duracion_agregar_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(34, 34, 34))
        );

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Hola");

        label_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lista_rep_playlist.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(lista_rep_playlist);

        reproducir_playlist.setText("Reproducir playlist");

        b_historial.setText("Historial");

        lista_artistas_a_seguir.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lista_artistas_a_seguir);

        jButton7.setText("Seguir artistas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setText("Crear playlist");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Agregar canciones al playlist");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton8.setText("Ver Artistas que sigue");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jLabel39.setText("Playlist");

        jLabel40.setText("Canciones del playlist");

        jLabel41.setText("Artistas a seguir");

        jButton13.setText("Reproducir");

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario.getContentPane());
        Usuario.getContentPane().setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barra_reproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(b_historial))
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addGroup(UsuarioLayout.createSequentialGroup()
                                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39)
                                    .addComponent(reproducir_playlist))
                                .addGap(18, 18, 18)
                                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13)
                                    .addComponent(jLabel40)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(UsuarioLayout.createSequentialGroup()
                                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8)
                                    .addComponent(jLabel41))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reproducir_playlist)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11))
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_historial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barra_reproduccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Crear playlist");

        jLabel36.setText("Nombre:");

        jLabel37.setText("Genero:");

        jLabel38.setText("Fecha de creacion");

        jButton12.setText("Crear playlist");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Crear_playlistLayout = new javax.swing.GroupLayout(Crear_playlist.getContentPane());
        Crear_playlist.getContentPane().setLayout(Crear_playlistLayout);
        Crear_playlistLayout.setHorizontalGroup(
            Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_playlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_playlistLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(nombre_crear_playlist))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_playlistLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(genero_crear_playlist))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Crear_playlistLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addGroup(Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_playlistLayout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fecha_crear_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
            .addGroup(Crear_playlistLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Crear_playlistLayout.setVerticalGroup(
            Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_playlistLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel35)
                .addGap(29, 29, 29)
                .addGroup(Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(nombre_crear_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(genero_crear_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Crear_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(fecha_crear_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(46, 46, 46))
        );

        lista_todas_las_canciones.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(lista_todas_las_canciones);

        jButton14.setText("Agregar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Agregar_canciones_al_playlistLayout = new javax.swing.GroupLayout(Agregar_canciones_al_playlist.getContentPane());
        Agregar_canciones_al_playlist.getContentPane().setLayout(Agregar_canciones_al_playlistLayout);
        Agregar_canciones_al_playlistLayout.setHorizontalGroup(
            Agregar_canciones_al_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_canciones_al_playlistLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(Agregar_canciones_al_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        Agregar_canciones_al_playlistLayout.setVerticalGroup(
            Agregar_canciones_al_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_canciones_al_playlistLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Usuario");

        jMenuItem1.setText("Registro Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        log_in_usuario.setText("Log in Usuario");
        log_in_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_in_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(log_in_usuario);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Artista");

        jMenuItem3.setText("Nuevo artista");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        log_in_artista.setText("Log in Artista");
        log_in_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_in_artistaActionPerformed(evt);
            }
        });
        jMenu3.add(log_in_artista);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Musica");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Log Out");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        Registro_usuario.setModal(true);
        Registro_usuario.pack();
        Registro_usuario.setLocationRelativeTo(this);
        Registro_usuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_usuarioActionPerformed
        // TODO add your handling code here:
    String nombre;
    String apellido;
    String usuario;
    String contrasena;
    Date fecha;
    nombre=nombre_nuevo_usuario.getText();
    apellido=apellido_nuevo_usuario.getText();
    usuario=usuario_nuevo_usuario.getText();
    contrasena=contrasena_nuevo_usuario.getText();
    fecha=fecha_nuevo_usuario.getSelectedDate().getTime();
    a_u.cargarArchivo();
    Usuario p=new Usuario(nombre,apellido,usuario,contrasena,fecha);
    a_u.setUsuario(p);
        try {
            a_u.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Usuario creado exitosamente");
    nombre_nuevo_usuario.setText("");
    apellido_nuevo_usuario.setText("");
    usuario_nuevo_usuario.setText("");
    contrasena_nuevo_usuario.setText("");
    log_in_usuario.setEnabled(true);
    Registro_usuario.dispose();
    }//GEN-LAST:event_crear_usuarioActionPerformed

    private void crear_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_usuario1ActionPerformed
        // TODO add your handling code here:
    String nombre;
    String apellido;
    String usuario;
    String contrasena;
    Date fecha;
    nombre=nombre_nuevo_artista.getText();
    apellido=apellido_nuevo_artista.getText();
    usuario=usuario_nuevo_artista.getText();
    contrasena=contrasena_nuevo_artista.getText();
    fecha=fecha_nuevo_artista.getSelectedDate().getTime();
    Artista p=new Artista(nombre,apellido,usuario,contrasena,fecha);
    a_a=new AdminArtista("./Artistas/artistas.dam");
    a_a.cargarArchivo();
    a_a.setArtistas(p);
        try {
            a_a.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Artista creado exitosamente");
    nombre_nuevo_artista.setText("");
    apellido_nuevo_artista.setText("");
    usuario_nuevo_artista.setText("");
    contrasena_nuevo_artista.setText("");
    log_in_artista.setEnabled(true);
    Registro_artista.dispose();
    }//GEN-LAST:event_crear_usuario1ActionPerformed

    private void log_in_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_in_usuarioActionPerformed
        // TODO add your handling code here:
        Log_in_usuario.setModal(true);
        Log_in_usuario.pack();
        Log_in_usuario.setLocationRelativeTo(this);
        Log_in_usuario.setVisible(true);
    }//GEN-LAST:event_log_in_usuarioActionPerformed

    private void log_in_artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_in_artistaActionPerformed
        // TODO add your handling code here:
        Log_in_artista.setModal(true);
        Log_in_artista.pack();
        Log_in_artista.setLocationRelativeTo(this);
        Log_in_artista.setVisible(true);
    }//GEN-LAST:event_log_in_artistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario=usuario_login_usuario.getText();
        String contrasena=contrasena_login_usuario.getText();
        int cont=0;
        a_u.cargarArchivo();
        for (int i = 0; i <a_u.getUsuario().size(); i++) 
        {
            if (a_u.getUsuario().get(i).getUsuario().equals(usuario) && a_u.getUsuario().get(i).getContrasena().equals(contrasena))
            {
                cont++;
                sub2=i;
            }
        }
        if (cont==1)
        {
            JOptionPane.showMessageDialog(this, "Bienvenido");
            RefrescarPlaylist();
            RefrescarArtistas();
            label_usuario.setText(a_u.getUsuario().get(sub2).getUsuario());
            Usuario.setModal(true);
            Usuario.pack();
            Usuario.setLocationRelativeTo(this);
            Usuario.setVisible(true);
            Log_in_usuario.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorecta");
            usuario_login_usuario.setText("");
            contrasena_login_usuario.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void RefrescarArtistas()
    {
        DefaultListModel modelo=(DefaultListModel)lista_artistas_a_seguir.getModel();
        modelo.clear();
        for (int i = 0; i <a_a.getArtistas().size(); i++) {
            modelo.addElement(a_a.getArtistas().get(i));  
        }
        lista_artistas_a_seguir.setModel(modelo);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String usuario=usuario_login_artista.getText();
        String contrasena=contrasena_login_artista.getText();
        int cont=0;
        int c=0;
        a_a.cargarArchivo();
       for (int i = 0; i <a_a.getArtistas().size(); i++) 
        {
            if (a_a.getArtistas().get(i).getUsuario().equals(usuario) && a_a.getArtistas().get(i).getContrasena().equals(contrasena))
            {
                cont++;
                c=i;
                sub=i;
                break;
            }
        }
        if (cont==1)
        {
            JOptionPane.showMessageDialog(this, "Bienvenido");
            Artista.setModal(true);
            Artista.pack();
            Artista.setLocationRelativeTo(this);
            label_atista.setText(usuario);
            usuario_actual=a_a.getArtistas().get(c);
            RefrescarAlbum();
            RefrescarSencillos();
            Artista.setVisible(true);
            Log_in_artista.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorecta");
            usuario_login_artista.setText("");
            contrasena_login_artista.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Registro_artista.setModal(true);
        Registro_artista.pack();
        Registro_artista.setLocationRelativeTo(this);
        Registro_artista.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Ha cerrado sesión exitosamente");
        usuario_actual=null;
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Agregar_sencillo.setModal(true);
        Agregar_sencillo.pack();
        Agregar_sencillo.setLocationRelativeTo(this);
        Agregar_sencillo.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    String nombre;
    int ano;
    Artista artista;
    int duracion;
    a_a.cargarArchivo();
    nombre=nombre_agregar_sencillo.getText();
    ano=Integer.parseInt(ano_agregar_sencillo.getText());
    artista=a_a.getArtistas().get(sub);
    duracion=Integer.parseInt(duracion_agregar_sencillo.getText());
    a_a.getArtistas().get(sub).getSencillos().add(new Canciones(nombre,ano,artista,duracion));
        try {
            a_a.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Sencillo creado exitosamente");
    RefrescarSencillos();
    nombre_agregar_sencillo.setText("");
    ano_agregar_sencillo.setText("");
    duracion_agregar_sencillo.setText("");
    Agregar_sencillo.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    String nombre;
    int ano;
    Artista artista;
    int duracion;
    nombre=nombre_agregar_cancion.getText();
    ano=Integer.parseInt(ano_agregar_cancion.getText());
    artista=(Artista)usuario_actual;
    duracion=Integer.parseInt(duracion_agregar_cancion.getText());
    a_a.cargarArchivo();
    a_a.getArtistas().get(sub).getAlbumes().get(lista_albumes.getSelectedIndex()).getCanciones().add(new Canciones(nombre,ano,artista,duracion));
        try {
            a_a.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Cancion creada exitosamente");
    RefrescarAlbum();
    nombre_agregar_cancion.setText("");
    ano_agregar_cancion.setText("");
    duracion_agregar_cancion.setText("");
    Agregar_cancion.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed
public void RefrescarAlbum()
{
    DefaultListModel modelo=(DefaultListModel)lista_albumes.getModel();
    modelo.clear();
    for (int i = 0; i <a_a.getArtistas().get(sub).getAlbumes().size(); i++) {
        modelo.addElement(a_a.getArtistas().get(sub).getAlbumes().get(i));
        lista_albumes.setModel(modelo);
    }
}
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Agregar_album.setModal(true);
        Agregar_album.pack();
        Agregar_album.setLocationRelativeTo(this);
        Agregar_album.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void crear_album_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_album_btActionPerformed
        // TODO add your handling code here:
    String nombre;
    int ano;
    Artista artista;
    nombre=nombre_crear_album.getText();
    ano=Integer.parseInt(ano_crear_album.getText());
    artista=a_a.getArtistas().get(sub);
    a_a.cargarArchivo();
    a_a.getArtistas().get(sub).getAlbumes().add(new Album(nombre,ano,artista));
        try {
            a_a.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Album creado exitosamente");
    RefrescarAlbum();
    nombre_crear_album.setText("");
    ano_crear_album.setText("");
    Agregar_album.dispose();
    
    }//GEN-LAST:event_crear_album_btActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Agregar_cancion.setModal(true);
        Agregar_cancion.pack();
        Agregar_cancion.setLocationRelativeTo(this);
        Agregar_cancion.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Crear_playlist.setModal(true);
        Crear_playlist.pack();
        Crear_playlist.setLocationRelativeTo(this);
        Crear_playlist.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    String nombre;
    String genero;
    Date fecha;
    nombre=nombre_crear_playlist.getText();
    genero=genero_crear_playlist.getText();
    fecha=fecha_crear_playlist.getSelectedDate().getTime();
//    a_u.cargarArchivo();
    a_u.getUsuario().get(sub2).getPlaylist().add(new Playlist(nombre,genero,fecha));
        try {
            a_u.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(this, "Playlist creada exitosamente");
    RefrescarPlaylist();
    nombre_crear_playlist.setText("");
    genero_crear_playlist.setText("");
    Crear_playlist.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Artista artista=a_a.getArtistas().get(lista_artistas_a_seguir.getSelectedIndex());
        a_u.cargarArchivo();
        a_u.getUsuario().get(sub2).getArtistas().add(artista);
        try {
            a_u.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Leotify.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel modelo=(DefaultListModel)lista_artistas_a_seguir.getModel();
        modelo.remove(lista_artistas_a_seguir.getSelectedIndex());
        lista_artistas_a_seguir.setModel(modelo);
        a_a.cargarArchivo();
        a_a.getArtistas().get(lista_artistas_a_seguir.getSelectedIndex()).getSeguidores().add(a_u.getUsuario().get(sub2));
        JOptionPane.showMessageDialog(this, "Ha seguido a ese artista");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        TodasLasCanciones();
        Agregar_canciones_al_playlist.setModal(true);
        Agregar_canciones_al_playlist.pack();
        Agregar_canciones_al_playlist.setLocationRelativeTo(this);
        Agregar_canciones_al_playlist.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
//        a_u.cargarArchivo();
//        a_u.getUsuario().get(sub2).getPlaylist().get(lista_rep_playlist.getSelectedIndex()).getCanciones().add();
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        a_a.cargarArchivo();
        for (int i = 0; i < a_u.getUsuario().size(); i++) {
            for (int j = 0; j <a_u.getUsuario().get(i).getArtistas().size(); j++) {
                
            }
            
        }
        JOptionPane.showMessageDialog(this, "HOla");
    }//GEN-LAST:event_jButton8ActionPerformed
    public void TodasLasCanciones()
    {
        DefaultListModel modelo=(DefaultListModel)lista_todas_las_canciones.getModel();
        modelo.clear();
        a_a.cargarArchivo();
        for (int i = 0; i <a_a.getArtistas().size(); i++) {
            for (int j = 0; j <a_a.getArtistas().get(i).getCanciones().size(); j++) {
                modelo.addElement(a_a.getArtistas().get(i).getCanciones().get(j));
                lista_todas_las_canciones.setModel(modelo);
            }
        }
    }
    
    public void RefrescarPlaylist()
    {
        DefaultListModel modelo=(DefaultListModel)lista_rep_playlist.getModel();
        modelo.clear();
        for (int i = 0; i <a_u.getUsuario().get(sub2).getPlaylist().size(); i++) {
            modelo.addElement(a_u.getUsuario().get(sub2).getPlaylist().get(i));
        }
        lista_rep_playlist.setModel(modelo);
    }
    
    
    public void RefrescarSencillos()
    {
        a_a.cargarArchivo();
        Artista p=a_a.getArtistas().get(sub);
        DefaultListModel modelo=(DefaultListModel)lista_sencillos.getModel();
        modelo.clear();
        for (int i = 0; i <p.getSencillos().size(); i++) {
            modelo.addElement(p.getSencillos().get(i));
            lista_sencillos.setModel(modelo);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leotify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_album;
    private javax.swing.JDialog Agregar_cancion;
    private javax.swing.JDialog Agregar_canciones_al_playlist;
    private javax.swing.JDialog Agregar_sencillo;
    private javax.swing.JDialog Artista;
    private javax.swing.JDialog Crear_playlist;
    private javax.swing.JDialog Log_in_artista;
    private javax.swing.JDialog Log_in_usuario;
    private javax.swing.JDialog Registro_artista;
    private javax.swing.JDialog Registro_usuario;
    private javax.swing.JDialog Usuario;
    private javax.swing.JTextField ano_agregar_cancion;
    private javax.swing.JTextField ano_agregar_sencillo;
    private javax.swing.JTextField ano_crear_album;
    private javax.swing.JTextField apellido_nuevo_artista;
    private javax.swing.JTextField apellido_nuevo_usuario;
    private javax.swing.JButton b_historial;
    private javax.swing.JProgressBar barra_reproduccion;
    private javax.swing.JPasswordField contrasena_login_artista;
    private javax.swing.JPasswordField contrasena_login_usuario;
    private javax.swing.JPasswordField contrasena_nuevo_artista;
    private javax.swing.JPasswordField contrasena_nuevo_usuario;
    private javax.swing.JButton crear_album_bt;
    private javax.swing.JButton crear_usuario;
    private javax.swing.JButton crear_usuario1;
    private javax.swing.JTextField duracion_agregar_cancion;
    private javax.swing.JTextField duracion_agregar_sencillo;
    private datechooser.beans.DateChooserCombo fecha_crear_playlist;
    private datechooser.beans.DateChooserCombo fecha_nuevo_artista;
    private datechooser.beans.DateChooserCombo fecha_nuevo_usuario;
    private javax.swing.JTextField genero_crear_playlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel label_atista;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JList<String> lista_albumes;
    private javax.swing.JList<String> lista_artistas_a_seguir;
    private javax.swing.JList<String> lista_rep_playlist;
    private javax.swing.JList<String> lista_seguidores;
    private javax.swing.JList<String> lista_sencillos;
    private javax.swing.JList<String> lista_todas_las_canciones;
    private javax.swing.JMenuItem log_in_artista;
    private javax.swing.JMenuItem log_in_usuario;
    private javax.swing.JTextField nombre_agregar_cancion;
    private javax.swing.JTextField nombre_agregar_sencillo;
    private javax.swing.JTextField nombre_crear_album;
    private javax.swing.JTextField nombre_crear_playlist;
    private javax.swing.JTextField nombre_nuevo_artista;
    private javax.swing.JTextField nombre_nuevo_usuario;
    private javax.swing.JButton reproducir_playlist;
    private javax.swing.JTextField usuario_login_artista;
    private javax.swing.JTextField usuario_login_usuario;
    private javax.swing.JTextField usuario_nuevo_artista;
    private javax.swing.JTextField usuario_nuevo_usuario;
    // End of variables declaration//GEN-END:variables
AdminArtista a_a=new AdminArtista("./Artistas/artistas.dam");
AdminUsuario a_u=new AdminUsuario("./Usuarios/usuario.dam");
ArrayList<Canciones>historial=new ArrayList();
Persona usuario_actual;
int sub;
int sub2;


}
